### ISSUE TITLE
Update tests to (oqs-)openssh v8

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/libssh#5]
After building [libssh v0.9.6](https://www.libssh.org/files/0.9/libssh-0.9.6.tar.xz) from scratch and using the [current, v8 openssh](https://github.com/openssh/openssh-portable) as the target for client-side testing (build libssh via `cmake -DUNIT_TESTING=ON -DCMAKE_BUILD_TYPE=Debug -DCLIENT_TESTING=ON  ..`) all tests pass, apparently indicating (upstream) libssh works/tests OK with openssh v8.

This leads me to conclude that it should be possible to upgrade oqs-libssh testing to using oqs-openssh (v8) for testing -- with the goal to eliminate continued support for oqs-openssh v7.

-> Doable & sensible?

As a side note, it would be good to document which (version of) libssh oqs-libssh has been branched off from. When checking the `git log` it seems to be an intermediate commit (d1abe26be3d61156976ab9bd679a9faee6afe8fc). Related question: Why is this repo no fork of https://git.libssh.org/projects/libssh.git?

**Comment by kevinmkane** [comment]
> This leads me to conclude that it should be possible to upgrade oqs-libssh testing to using oqs-openssh (v8) for testing -- with the goal to eliminate continued support for oqs-openssh v7.
> 
> -> Doable & sensible?

I expect so. At a quick glance it looked like the on-wire formats for PQ/hybrid keys and messages didn't change from v7 to v8, and so I thought there was a good chance these were compatible, and they should still interop over whatever intersection of ciphersuites remain common between the versions.

I first want to look at updating the templates for libssh to match v8's ciphersuites exactly instead of the intersection, so we can test interop with all of them. This would also eliminate the need for v7. If this proves problematic for some reason, then I'll look at just swapping v8 in for the tests.

> As a side note, it would be good to document which (version of) libssh oqs-libssh has been branched off from. When checking the `git log` it seems to be an intermediate commit ([d1abe26](https://github.com/open-quantum-safe/libssh/commit/d1abe26be3d61156976ab9bd679a9faee6afe8fc)). Related question: Why is this repo no fork of https://git.libssh.org/projects/libssh.git?

The `master` branch here is the upstream's master branch, although I copied it manually. The local version of `master` is also the current branch-off point for this work. I can note that commit ID in the README. I didn't duplicate the other branches and tags from upstream, as I didn't see a need. (If there's a way in GitHub to make a fork from a repo not hosted on GitHub, I was unaware of it.) So even if it's not an "official" work as far as GitHub is concerned, the history is still there to allow merging libssh's official master in to take updates when we want.

There have been no official releases of 0.10 yet, so I have no tag to snap to. The branch-off pointed ended up being the head of master at the time. A potentially interested customer also said they tracked `master` for their use, rather than the 0.9 release branch, and so I did so as well.

**Comment by dstebila** [comment]
So are you saying that you think the v7 and v8 branches *should* be incompatible but seem not to be?  If so, that's weird and worth investigating.

**Comment by kevinmkane** [comment]
I just realized I misread what @baentsch said. He built and ran the official libssh against OQS-OpenSSH v8, and that worked. That is not surprising. Somehow I had it in my head he ran the OQS fork against it and it worked.

So, we haven't yet experimentally verified the branches are incompatible, but this alone suggests we should expect them to be.

And this means it looks unlikely we can use OQS-OpenSSH v8 to test against the current OQS-libssh as-is, and the latter will need updating to be compatible.

**Comment by baentsch** [comment]
> He built and ran the official libssh against OQS-OpenSSH v8, and that worked. 

Little correction: I built and ran the official libssh against openssh v8 and that worked. No OQS involved. My goal was to ascertain that (current) libssh tests OK against (current) openssh. Hence the question whether it shouldn't be possible to (successfully) test oqs-libssh against oqs-openssh (v8).

> the latter will need updating to be compatible.

This surely is right -- so maybe it would be more correct to re-title this issue to read "update libssh to current upstream libssh code base" (and expecting the test cases afterwards to immediately work OK with oqs-openssh (v8)).
